import { useState } from 'react'
import { Icon } from '../components/Icon'

type NodeKey = 'internet' | 'route53' | 'cloudfront' | 'vpc' | 'ec2' | 'rds'

const nodes: Record<NodeKey, { title: string; layer: string; icon: string; endpoint: string; purpose: string; latency: string; address: string }> = {
  internet: { title: 'Internet', layer: 'Origen', icon: 'language', endpoint: 'Usuarios globales', purpose: 'Punto de origen del tráfico HTTPS de la aplicación.', latency: '—', address: '0.0.0.0/0' },
  route53: { title: 'Amazon Route 53', layer: 'DNS', icon: 'travel_explore', endpoint: 'app.cloudops.com', purpose: 'Resuelve el dominio público y dirige las solicitudes al CDN.', latency: '24 ms', address: 'Alias A/AAAA' },
  cloudfront: { title: 'Amazon CloudFront', layer: 'Edge', icon: 'public', endpoint: 'd2x-cloudfront.net', purpose: 'Entrega contenido desde ubicaciones de borde y protege el origen.', latency: '11 ms', address: 'HTTPS · TLS 1.3' },
  vpc: { title: 'Amazon VPC', layer: 'Red', icon: 'hub', endpoint: 'production-vpc', purpose: 'Aísla los recursos de aplicación y datos en subredes controladas.', latency: '2 ms', address: '10.0.0.0/16' },
  ec2: { title: 'Amazon EC2', layer: 'Aplicación', icon: 'dns', endpoint: 'app-server-asg', purpose: 'Procesa las solicitudes y ejecuta la aplicación.', latency: '4 ms', address: '10.0.1.0/24' },
  rds: { title: 'Amazon RDS', layer: 'Datos', icon: 'storage', endpoint: 'cloudops-production', purpose: 'Mantiene los datos transaccionales en una subred privada.', latency: '7 ms', address: '10.0.2.0/24' },
}

const trace: Array<{ key: NodeKey; step: string; destination: string; policy: string }> = [
  { key: 'internet', step: '01', destination: 'Entrada pública', policy: 'HTTPS :443' },
  { key: 'route53', step: '02', destination: 'Hosted Zone', policy: 'Alias routing' },
  { key: 'cloudfront', step: '03', destination: 'Distribución global', policy: 'WAF + TLS' },
  { key: 'vpc', step: '04', destination: 'VPC Producción', policy: 'IGW + Routes' },
  { key: 'ec2', step: '05A', destination: 'Subred aplicación', policy: 'SG web-app' },
  { key: 'rds', step: '05B', destination: 'Subred de datos', policy: 'SG database' },
]

function NetworkMetric({ label, value, detail, icon, tone }: { label: string; value: string; detail: string; icon: string; tone: string }) {
  return <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-[0_1px_2px_rgba(15,23,42,0.04)]"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-slate-400">{label}</p><strong className="mt-2 block text-xl font-extrabold text-slate-800">{value}</strong><p className="mt-1 text-xs text-slate-500">{detail}</p></div><div className={`flex size-9 items-center justify-center rounded-xl ${tone}`}><Icon name={icon} className="text-[18px]" /></div></div></article>
}

export function Network() {
  const [selectedKey, setSelectedKey] = useState<NodeKey>('route53')
  const [testing, setTesting] = useState(false)
  const [lastTest, setLastTest] = useState('Hace 2 minutos')
  const selected = nodes[selectedKey]

  const validate = () => {
    setTesting(true)
    window.setTimeout(() => { setTesting(false); setLastTest('Ahora') }, 800)
  }

  return (
    <div className="flex flex-col gap-6">
      <header className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[11px] font-extrabold uppercase tracking-[0.16em] text-orange-600">Arquitectura de red</p><h2 className="mt-1 text-3xl font-bold tracking-[-0.045em] text-slate-800 sm:text-[32px]">Conectividad de producción</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Inspecciona la ruta activa, los controles aplicados y los recursos internos de la VPC.</p></div><button type="button" onClick={validate} disabled={testing} className="inline-flex w-full items-center justify-center gap-2 rounded-xl border border-orange-500 bg-orange-500 px-4 py-2.5 text-sm font-bold text-slate-950 transition hover:bg-orange-400 disabled:opacity-70 sm:w-auto"><Icon name="network_check" className={`text-[18px] ${testing ? 'animate-pulse' : ''}`} />{testing ? 'Validando ruta...' : 'Validar conectividad'}</button></header>

      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><NetworkMetric label="Estado del flujo" value="Operativo" detail={`Validado ${lastTest.toLowerCase()}`} icon="check_circle" tone="bg-emerald-50 text-emerald-600" /><NetworkMetric label="Latencia total" value="42 ms" detail="Objetivo menor a 80 ms" icon="speed" tone="bg-blue-50 text-blue-600" /><NetworkMetric label="Disponibilidad" value="99.99%" detail="Últimos 30 días" icon="monitor_heart" tone="bg-violet-50 text-violet-600" /><NetworkMetric label="Controles" value="8/9" detail="1 ACL requiere revisión" icon="shield" tone="bg-amber-50 text-amber-600" /></div>

      <div className="grid min-w-0 grid-cols-1 gap-5 lg:grid-cols-[minmax(0,1.35fr)_minmax(300px,.65fr)]">
        <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_1px_2px_rgba(15,23,42,0.04),0_12px_30px_rgba(15,23,42,0.05)]"><div className="flex flex-col gap-2 border-b border-slate-200 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="text-lg font-bold text-slate-800">Ruta activa de tráfico</h3><p className="mt-1 text-sm text-slate-500">Seguimiento desde Internet hasta aplicación y datos.</p></div><span className="inline-flex w-fit items-center gap-1.5 rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-bold text-emerald-700"><span className="size-1.5 rounded-full bg-emerald-500" />6 saltos disponibles</span></div>
          <div className="hidden grid-cols-[62px_minmax(0,1.2fr)_minmax(0,.85fr)_minmax(0,.8fr)_70px] border-b border-slate-200 bg-slate-50 px-4 py-2.5 text-[9px] font-extrabold uppercase tracking-[0.1em] text-slate-400 sm:grid"><span>Salto</span><span>Servicio</span><span>Destino</span><span>Control</span><span className="text-right">Latencia</span></div>
          <div className="divide-y divide-slate-100">{trace.map((row) => { const node = nodes[row.key]; const selectedRow = selectedKey === row.key; return <button type="button" key={row.key} onClick={() => setSelectedKey(row.key)} aria-pressed={selectedRow} className={`grid w-full grid-cols-[44px_minmax(0,1fr)_auto] items-center gap-3 px-4 py-3 text-left transition sm:grid-cols-[62px_minmax(0,1.2fr)_minmax(0,.85fr)_minmax(0,.8fr)_70px] ${selectedRow ? 'bg-orange-50/70 ring-1 ring-inset ring-orange-200' : 'hover:bg-slate-50'}`}><span className="flex size-8 items-center justify-center rounded-lg bg-slate-100 font-mono text-[10px] font-extrabold text-slate-600">{row.step}</span><span className="flex min-w-0 items-center gap-3"><span className={`flex size-9 shrink-0 items-center justify-center rounded-lg ${selectedRow ? 'bg-orange-100 text-orange-700' : 'bg-blue-50 text-blue-600'}`}><Icon name={node.icon} className="text-[18px]" /></span><span className="min-w-0"><strong className="block truncate text-sm text-slate-800">{node.title}</strong><span className="mt-0.5 block truncate text-[10px] text-slate-400">{node.endpoint}</span></span></span><span className="hidden text-xs font-bold text-slate-600 sm:block">{row.destination}</span><span className="hidden text-[11px] text-slate-500 sm:block">{row.policy}</span><span className="text-right text-xs font-extrabold text-slate-700">{node.latency}</span></button> })}</div>
        </section>

        <aside className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,0.04)] sm:p-6 lg:sticky lg:top-24"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-slate-400">Recurso seleccionado</p><h3 className="mt-1.5 text-xl font-bold text-slate-800">{selected.title}</h3></div><span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-bold text-emerald-700"><span className="size-1.5 rounded-full bg-emerald-500" />Activo</span></div><div className="mt-5 flex items-start gap-3 rounded-xl border border-orange-100 bg-orange-50/60 p-4"><div className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-white text-orange-600 shadow-sm"><Icon name={selected.icon} className="text-[22px]" /></div><div><p className="text-[10px] font-extrabold uppercase tracking-[0.1em] text-orange-700">{selected.layer}</p><p className="mt-1 text-sm font-bold text-slate-800">{selected.endpoint}</p></div></div><dl className="mt-4 space-y-3"><div className="rounded-xl border border-slate-100 bg-slate-50 p-3"><dt className="text-[9px] font-extrabold uppercase tracking-[0.1em] text-slate-400">Función</dt><dd className="mt-1.5 text-sm font-bold leading-5 text-slate-700">{selected.purpose}</dd></div><div className="grid grid-cols-2 gap-2"><div className="rounded-xl border border-slate-100 bg-slate-50 p-3"><dt className="text-[9px] font-extrabold uppercase text-slate-400">Dirección</dt><dd className="mt-1.5 truncate font-mono text-[11px] font-bold text-slate-700">{selected.address}</dd></div><div className="rounded-xl border border-slate-100 bg-slate-50 p-3"><dt className="text-[9px] font-extrabold uppercase text-slate-400">Latencia</dt><dd className="mt-1.5 text-sm font-bold text-slate-700">{selected.latency}</dd></div></div></dl><div className="mt-5 border-t border-slate-100 pt-4"><p className="text-xs font-bold text-slate-800">Verificaciones</p><div className="mt-3 space-y-2">{['Cifrado en tránsito', 'Métricas habilitadas', 'Acceso controlado'].map((item) => <div key={item} className="flex items-center gap-2 text-xs text-slate-600"><Icon name="check_circle" className="text-[16px] text-emerald-600" />{item}</div>)}</div></div></aside>
      </div>

      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,0.04)] sm:p-6"><div className="flex flex-col gap-3 border-b border-slate-100 pb-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><div className="flex size-9 items-center justify-center rounded-lg bg-blue-50 text-blue-600"><Icon name="hub" className="text-[18px]" /></div><div><h3 className="text-lg font-bold text-slate-800">production-vpc</h3><p className="mt-0.5 font-mono text-[10px] text-slate-500">10.0.0.0/16 · us-east-1 · 2 Availability Zones</p></div></div></div><div className="flex flex-wrap gap-2"><span className="rounded-lg border border-slate-200 bg-slate-50 px-2.5 py-1.5 text-[10px] font-bold text-slate-600">Route Table asociada</span><span className="rounded-lg border border-emerald-200 bg-emerald-50 px-2.5 py-1.5 text-[10px] font-bold text-emerald-700">Security Groups activos</span></div></div>
        <div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-blue-200 bg-blue-50/30 p-4"><div className="flex items-center justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-blue-700">Zona de disponibilidad A</p><p className="mt-1 font-mono text-[9px] text-slate-500">us-east-1a</p></div><span className="rounded-md bg-blue-100 px-2 py-1 text-[9px] font-bold text-blue-700">PÚBLICA</span></div><button type="button" onClick={() => setSelectedKey('ec2')} className={`mt-4 flex w-full items-center gap-3 rounded-xl border bg-white p-3 text-left transition hover:border-orange-300 ${selectedKey === 'ec2' ? 'border-orange-300 ring-2 ring-orange-100' : 'border-slate-200'}`}><div className="flex size-10 items-center justify-center rounded-lg bg-orange-50 text-orange-600"><Icon name="dns" className="text-[19px]" /></div><span className="min-w-0 flex-1"><strong className="block text-sm text-slate-800">EC2 Auto Scaling Group</strong><span className="mt-0.5 block text-[10px] text-slate-500">3 instancias · 10.0.1.0/24</span></span><span className="inline-flex items-center gap-1 text-[10px] font-bold text-emerald-700"><i className="size-1.5 rounded-full bg-emerald-500" />Healthy</span></button><div className="mt-3 grid grid-cols-3 gap-2 text-center">{['i-0a31', 'i-0b72', 'i-0c18'].map((id) => <div key={id} className="rounded-lg border border-slate-200 bg-white px-2 py-2"><span className="block font-mono text-[9px] font-bold text-slate-600">{id}</span><span className="mt-1 inline-flex items-center gap-1 text-[8px] text-emerald-700"><i className="size-1 rounded-full bg-emerald-500" />running</span></div>)}</div></div>
          <div className="rounded-xl border border-emerald-200 bg-emerald-50/30 p-4"><div className="flex items-center justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-emerald-700">Zona de disponibilidad B</p><p className="mt-1 font-mono text-[9px] text-slate-500">us-east-1b</p></div><span className="rounded-md bg-emerald-100 px-2 py-1 text-[9px] font-bold text-emerald-700">PRIVADA</span></div><button type="button" onClick={() => setSelectedKey('rds')} className={`mt-4 flex w-full items-center gap-3 rounded-xl border bg-white p-3 text-left transition hover:border-orange-300 ${selectedKey === 'rds' ? 'border-orange-300 ring-2 ring-orange-100' : 'border-slate-200'}`}><div className="flex size-10 items-center justify-center rounded-lg bg-emerald-50 text-emerald-600"><Icon name="storage" className="text-[19px]" /></div><span className="min-w-0 flex-1"><strong className="block text-sm text-slate-800">RDS PostgreSQL</strong><span className="mt-0.5 block text-[10px] text-slate-500">Multi-AZ · 10.0.2.0/24</span></span><span className="inline-flex items-center gap-1 text-[10px] font-bold text-emerald-700"><i className="size-1.5 rounded-full bg-emerald-500" />Available</span></button><div className="mt-3 rounded-lg border border-slate-200 bg-white p-3"><div className="flex items-center justify-between text-[10px]"><span className="font-bold text-slate-600">Acceso desde aplicación</span><strong className="text-emerald-700">Permitido :5432</strong></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-[64%] rounded-full bg-emerald-500" /></div><p className="mt-1.5 text-[9px] text-slate-400">64 conexiones activas de 100</p></div></div></div>
        <div className="mt-4 flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50/70 px-4 py-3"><Icon name="warning" className="mt-0.5 text-[17px] text-amber-600" /><div><p className="text-xs font-bold text-amber-900">1 Network ACL requiere revisión</p><p className="mt-1 text-[11px] leading-5 text-amber-800">La regla de salida temporal debe expirar antes del siguiente despliegue.</p></div></div>
      </section>
    </div>
  )
}
