import { useMemo, useState } from 'react'
import { services } from '../data/cloudData'
import { Icon } from '../components/Icon'
import { Badge } from '../components/ui/badge'
import { Button } from '../components/ui/button'
import { Input } from '../components/ui/input'

const categoryStyles: Record<string, { icon: string; surface: string }> = {
  Compute: { icon: 'dns', surface: 'bg-orange-50 text-orange-600 border-orange-200' },
  Storage: { icon: 'database', surface: 'bg-emerald-50 text-emerald-600 border-emerald-200' },
  Database: { icon: 'storage', surface: 'bg-blue-50 text-blue-600 border-blue-200' },
  Security: { icon: 'security', surface: 'bg-red-50 text-red-600 border-red-200' },
  Networking: { icon: 'hub', surface: 'bg-violet-50 text-violet-600 border-violet-200' },
  Delivery: { icon: 'public', surface: 'bg-cyan-50 text-cyan-600 border-cyan-200' },
}

function UsageBadge({ status }: { status: string }) {
  const classes = status === 'En uso' ? 'bg-emerald-50 text-emerald-700' : status === 'Revisión' ? 'bg-amber-50 text-amber-700' : 'bg-blue-50 text-blue-700'
  const dot = status === 'En uso' ? 'bg-emerald-500' : status === 'Revisión' ? 'bg-amber-500' : 'bg-blue-500'
  return <Badge variant="outline" className={`h-auto border-0 px-2.5 py-1 text-[10px] font-bold ${classes}`}><span className={`size-1.5 rounded-full ${dot}`} />{status}</Badge>
}

function CatalogMetric({ label, value, detail, icon, tone }: { label: string; value: string; detail: string; icon: string; tone: string }) {
  return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-[0_1px_2px_rgba(15,23,42,0.04),0_10px_26px_rgba(15,23,42,0.04)]"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-slate-400">{label}</p><strong className="mt-2 block text-2xl tracking-[-0.04em] text-slate-800">{value}</strong><p className="mt-1 text-xs text-slate-500">{detail}</p></div><div className={`flex size-10 items-center justify-center rounded-xl ${tone}`}><Icon name={icon} className="text-[20px]" /></div></div></div>
}

export function Services() {
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('Todos')
  const [selectedId, setSelectedId] = useState(services[0].id)
  const categories = ['Todos', ...Array.from(new Set(services.map((service) => service.category)))]
  const filteredServices = useMemo(() => services.filter((service) => (category === 'Todos' || service.category === category) && `${service.name} ${service.shortName} ${service.description} ${service.purpose}`.toLowerCase().includes(query.toLowerCase())), [category, query])
  const selectedService = services.find((service) => service.id === selectedId) ?? services[0]
  const selectedStyle = categoryStyles[selectedService.category] ?? { icon: selectedService.icon, surface: 'bg-slate-50 text-slate-600 border-slate-200' }
  const activeServices = services.filter((service) => service.status === 'En uso').length

  return (
    <div className="flex flex-col gap-6">
      <header><p className="text-[11px] font-extrabold uppercase tracking-[0.16em] text-orange-600">Catálogo de servicios</p><h2 className="mt-1 text-3xl font-bold tracking-[-0.045em] text-slate-800 sm:text-[32px]">Servicios AWS</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Consulta los servicios disponibles, su función dentro de la arquitectura y el estado de utilización actual.</p></header>

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><CatalogMetric label="Servicios registrados" value={`${services.length}`} detail="Catálogo CloudOps" icon="apps" tone="bg-orange-50 text-orange-600" /><CatalogMetric label="Servicios en uso" value={`${activeServices}`} detail="Integrados en la solución" icon="check_circle" tone="bg-emerald-50 text-emerald-600" /><CatalogMetric label="Categorías" value={`${categories.length - 1}`} detail="Áreas funcionales" icon="category" tone="bg-blue-50 text-blue-600" /><CatalogMetric label="Disponibilidad" value="99.99%" detail="Promedio de servicios" icon="monitor_heart" tone="bg-violet-50 text-violet-600" /></div>

      <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-[0_1px_2px_rgba(15,23,42,0.04)] sm:p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="relative min-w-0 flex-1 lg:max-w-md"><Icon name="search" className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-[18px] text-slate-400" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por nombre, función o descripción" className="h-auto rounded-xl border-slate-300 py-3 pl-10 pr-3 text-sm shadow-none focus-visible:border-orange-400 focus-visible:ring-orange-100" /></div><div className="flex flex-wrap gap-2">{categories.map((item) => <Button type="button" size="sm" variant={category === item ? 'default' : 'outline'} key={item} onClick={() => setCategory(item)} className={`rounded-full text-xs font-bold ${category === item ? 'border-[#ff9900] bg-orange-50 text-orange-700 hover:bg-orange-100' : 'border-slate-200 text-slate-500 hover:text-slate-700'}`}>{item}</Button>)}</div></div><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-4"><span className="text-xs text-slate-500"><strong className="text-slate-800">{filteredServices.length}</strong> servicios visibles</span><span className="hidden items-center gap-1.5 text-[10px] font-bold text-slate-400 sm:inline-flex"><span className="size-1.5 rounded-full bg-emerald-500" />Catálogo sincronizado</span></div></section>

      <div className="grid min-w-0 grid-cols-1 items-start gap-5 lg:grid-cols-3">
        <section className="min-w-0 lg:col-span-2"><div className="grid gap-4 sm:grid-cols-2">{filteredServices.map((service) => { const style = categoryStyles[service.category] ?? { icon: service.icon, surface: 'bg-slate-50 text-slate-600 border-slate-200' }; const isSelected = selectedService.id === service.id; return <button type="button" key={service.id} aria-pressed={isSelected} onClick={() => setSelectedId(service.id)} className={`group min-w-0 rounded-2xl border bg-white p-5 text-left shadow-[0_1px_2px_rgba(15,23,42,0.04),0_10px_26px_rgba(15,23,42,0.04)] transition hover:-translate-y-0.5 hover:shadow-md ${isSelected ? 'border-orange-300 ring-2 ring-orange-100' : 'border-slate-200'}`}><div className="flex items-start justify-between gap-3"><div className={`flex size-11 shrink-0 items-center justify-center rounded-xl border ${style.surface}`}><Icon name={service.icon || style.icon} className="text-[21px]" /></div><UsageBadge status={service.status} /></div><div className="mt-4"><div className="flex items-center gap-2"><h3 className="truncate text-base font-bold text-slate-800">{service.name}</h3><span className="rounded-md bg-slate-100 px-2 py-0.5 text-[9px] font-extrabold text-slate-500">{service.shortName}</span></div><p className="mt-1 text-[10px] font-extrabold uppercase tracking-[0.12em] text-slate-400">{service.category}</p><p className="mt-3 line-clamp-2 text-sm leading-6 text-slate-500">{service.description}</p></div><div className="mt-4 border-t border-slate-100 pt-4"><p className="text-[9px] font-extrabold uppercase tracking-[0.1em] text-slate-400">Función principal</p><div className="mt-2 flex items-start justify-between gap-3"><span className="text-xs font-bold leading-5 text-slate-700">{service.purpose}</span><Icon name="arrow_forward" className={`mt-0.5 shrink-0 text-[17px] transition ${isSelected ? 'text-orange-600' : 'text-slate-300 group-hover:text-orange-500'}`} /></div></div></button>})}</div>{filteredServices.length === 0 && <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><div className="mx-auto flex size-12 items-center justify-center rounded-2xl bg-slate-100 text-slate-400"><Icon name="search_off" className="text-[24px]" /></div><h3 className="mt-4 text-base font-bold text-slate-800">No encontramos servicios</h3><p className="mt-1 text-sm text-slate-500">Prueba otro término o selecciona una categoría diferente.</p></div>}</section>

        <aside className="min-w-0 rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,0.04),0_12px_30px_rgba(15,23,42,0.05)] sm:p-6 lg:sticky lg:top-24"><div className="flex items-start justify-between gap-3"><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-slate-400">Detalle del servicio</p><UsageBadge status={selectedService.status} /></div><div className="mt-5 flex items-start gap-3"><div className={`flex size-12 shrink-0 items-center justify-center rounded-xl border ${selectedStyle.surface}`}><Icon name={selectedService.icon || selectedStyle.icon} className="text-[24px]" /></div><div className="min-w-0"><h3 className="truncate text-xl font-bold tracking-[-0.03em] text-slate-800">{selectedService.name}</h3><p className="mt-1 text-xs font-bold text-slate-500">{selectedService.category}</p></div></div><div className="mt-5 rounded-xl border border-slate-100 bg-slate-50/70 p-4"><p className="text-[9px] font-extrabold uppercase tracking-[0.1em] text-slate-400">Descripción</p><p className="mt-2 text-sm leading-6 text-slate-600">{selectedService.description}</p></div><dl className="mt-4 space-y-3"><div className="rounded-xl border border-slate-100 p-3"><dt className="text-[9px] font-extrabold uppercase tracking-[0.1em] text-slate-400">Función principal</dt><dd className="mt-1.5 text-sm font-bold leading-5 text-slate-700">{selectedService.purpose}</dd></div><div className="grid grid-cols-2 gap-2"><div className="rounded-xl border border-slate-100 p-3"><dt className="text-[9px] font-extrabold uppercase tracking-[0.1em] text-slate-400">Código</dt><dd className="mt-1.5 text-xs font-bold text-slate-700">{selectedService.shortName}</dd></div><div className="rounded-xl border border-slate-100 p-3"><dt className="text-[9px] font-extrabold uppercase tracking-[0.1em] text-slate-400">Estado</dt><dd className="mt-1.5 text-xs font-bold text-slate-700">{selectedService.status}</dd></div></div></dl><div className="mt-5 border-t border-slate-100 pt-4"><p className="text-xs font-bold text-slate-800">Integración actual</p><div className="mt-3 space-y-2">{['Monitoreo habilitado', 'Etiquetas configuradas', 'Políticas revisadas'].map((item) => <div key={item} className="flex items-center gap-2 text-xs text-slate-600"><Icon name="check_circle" className="text-[16px] text-emerald-600" /><span>{item}</span></div>)}</div></div><div className="mt-5 rounded-xl border border-orange-200 bg-orange-50/60 p-3"><div className="flex items-start gap-2"><Icon name="tips_and_updates" className="text-[17px] text-orange-600" /><div><p className="text-xs font-bold text-orange-900">Uso recomendado</p><p className="mt-1 text-[11px] leading-5 text-orange-800">Mantén métricas, etiquetas y permisos actualizados para controlar costos y seguridad.</p></div></div></div></aside>
      </div>
    </div>
  )
}
